server:
  port: 8080
  servlet:
    context-path: /app

spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/geek_spring_2
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  jackson:
    serialization:
      indent_output: true
  liquibase:
    change-log: 'classpath:/db/database-spring2-changelog.xml'

logging:
  level:
    root: debug
    liquibase: debug

#liquibase:
#  change-log: 'classpath:database-spring2-changelog.xml'
#spring:
#  liquibase:
#liquibase:
#  host: jdbc:postgresql://192.168.99.100:5432/geek_spring_2
